version: '3.4'

services:
  st-genetics-farm-db:
    container_name: "st-genetics-farm-db"
    image: "julianccortes/stgenetics-farm-db:1.0"
    environment:
      - "MSSQL_SA_PASSWORD=Qwerty123#"
      - "TZ=America/Bogota"
      - "ACCEPT_EULA=Y"  
    ports:
      - "21433:1433"
    networks:
      - stgeneticsnet  
 
networks:
  stgeneticsnet:
    driver: bridge    

